from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI(object):
	def setupUi(self, UI):
		UI.setObjectName("UI")
		UI.setWindowModality(QtCore.Qt.NonModal)
		UI.resize(1109, 743)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(UI.sizePolicy().hasHeightForWidth())
		UI.setSizePolicy(sizePolicy)
		UI.setMinimumSize(QtCore.QSize(1109, 743))
		UI.setMouseTracking(False)
		UI.setTabletTracking(False)
		UI.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		UI.setWindowIcon(icon)
		UI.setLayoutDirection(QtCore.Qt.LeftToRight)
		UI.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.centralwidget = QtWidgets.QWidget(UI)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout_4.setObjectName("gridLayout_4")


		self.scrollAreaCont = QtWidgets.QVBoxLayout()
		self.scrollAreaCont.setObjectName("scrollAreaCont")
		self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
		self.scrollArea.setSizePolicy(sizePolicy)
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 358, 551))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.sliderCont = QtWidgets.QWidget(self.scrollAreaWidgetContents)
		self.sliderCont.setObjectName("sliderCont")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sliderCont)
		self.verticalLayout_5.setObjectName("verticalLayout_5")



		self.sliderBox = QtWidgets.QWidget(self.sliderCont)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.sliderBox.sizePolicy().hasHeightForWidth())
		self.sliderBox.setSizePolicy(sizePolicy)
		self.sliderBox.setMinimumSize(QtCore.QSize(0, 60))
		self.sliderBox.setObjectName("sliderBox")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sliderBox)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.label = QtWidgets.QLabel(self.sliderBox)
		self.label.setObjectName("label")
		self.verticalLayout_4.addWidget(self.label)
		self.horizontalSlider = QtWidgets.QSlider(self.sliderBox)
		self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSlider.setObjectName("horizontalSlider")
		self.verticalLayout_4.addWidget(self.horizontalSlider)
		self.verticalLayout_5.addWidget(self.sliderBox)
		self.verticalLayout_3.addWidget(self.sliderCont)
		self.scrollArea.setWidget(self.scrollAreaWidgetContents)
		self.scrollAreaCont.addWidget(self.scrollArea)
		self.gridLayout_4.addLayout(self.scrollAreaCont, 2, 0, 12, 1)


		self.comboCont = QtWidgets.QHBoxLayout()
		self.comboCont.setObjectName("comboCont")
		self.comboBox = QtWidgets.QComboBox(self.centralwidget)
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboCont.addWidget(self.comboBox)
		self.gridLayout_4.addLayout(self.comboCont, 0, 0, 1, 1)


		self.btnCont = QtWidgets.QHBoxLayout()
		self.btnCont.setObjectName("btnCont")
		self.rndCont = QtWidgets.QHBoxLayout()
		self.rndCont.setObjectName("rndCont")
		self.rndBtn = QtWidgets.QPushButton(self.centralwidget)
		self.rndBtn.setObjectName("rndBtn")
		self.rndCont.addWidget(self.rndBtn)
		self.btnCont.addLayout(self.rndCont)
		self.avgCont = QtWidgets.QHBoxLayout()
		self.avgCont.setObjectName("avgCont")
		self.avgBtn = QtWidgets.QPushButton(self.centralwidget)
		self.avgBtn.setObjectName("avgBtn")
		self.avgCont.addWidget(self.avgBtn)
		self.btnCont.addLayout(self.avgCont)
		self.gridLayout_4.addLayout(self.btnCont, 14, 0, 1, 1)




		self.layerCont = QtWidgets.QVBoxLayout()
		self.layerCont.setObjectName("layerCont")
		self.layerBox = QtWidgets.QFrame(self.centralwidget)
		self.layerBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.layerBox.setFrameShadow(QtWidgets.QFrame.Raised)
		self.layerBox.setObjectName("layerBox")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layerBox)
		self.verticalLayout.setObjectName("verticalLayout")
		self.layerLabel = QtWidgets.QLabel(self.layerBox)
		self.layerLabel.setObjectName("layerLabel")
		self.verticalLayout.addWidget(self.layerLabel)
		self.layerSlider = QtWidgets.QSlider(self.layerBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.layerSlider.sizePolicy().hasHeightForWidth())
		self.layerSlider.setSizePolicy(sizePolicy)
		self.layerSlider.setOrientation(QtCore.Qt.Horizontal)
		self.layerSlider.setObjectName("layerSlider")
		self.verticalLayout.addWidget(self.layerSlider)
		self.layerCont.addWidget(self.layerBox)
		self.gridLayout_4.addLayout(self.layerCont, 1, 0, 1, 1)


		
		self.imgBoxCont = QtWidgets.QWidget(self.centralwidget)
		self.imgBoxCont.setObjectName("imgBoxCont")
		self.imgCont = QtWidgets.QGridLayout(self.imgBoxCont)
		self.imgCont.setObjectName("imgCont")
		self.imgBox = QtWidgets.QLabel(self.imgBoxCont)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.imgBox.sizePolicy().hasHeightForWidth())
		self.imgBox.setSizePolicy(sizePolicy)
		self.imgBox.setMaximumSize(QtCore.QSize(720, 720))
		self.imgBox.setText("")
		self.imgBox.setPixmap(QtGui.QPixmap("avatar.jpeg"))
		self.imgBox.setScaledContents(True)
		self.imgBox.setObjectName("imgBox")
		self.imgCont.addWidget(self.imgBox, 0, 0, 1, 1)
		self.gridLayout_4.addWidget(self.imgBoxCont, 0, 1, 15, 2)
		UI.setCentralWidget(self.centralwidget)

		self.retranslateUi(UI)
		QtCore.QMetaObject.connectSlotsByName(UI)

	def retranslateUi(self, UI):
		_translate = QtCore.QCoreApplication.translate
		UI.setWindowTitle(_translate("UI", "MainWindow"))
		self.label.setText(_translate("UI", "TextLabel"))
		self.comboBox.setItemText(0, _translate("UI", "Faces"))
		self.comboBox.setItemText(1, _translate("UI", "Cars"))
		self.rndBtn.setText(_translate("UI", "Randomize"))
		self.avgBtn.setText(_translate("UI", "Average"))
		self.layerLabel.setText(_translate("UI", "Layers"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	UI = QtWidgets.QMainWindow()
	ui = Ui_UI()
	ui.setupUi(UI)
	UI.show()
	sys.exit(app.exec_())